//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.UserControls {
    
    public partial class CouponDetailList {
        protected System.Web.UI.WebControls.Label lbPageFirst;
        protected System.Web.UI.WebControls.Label lblDisplayText;
        protected System.Web.UI.WebControls.Label lblPageText;
    }
}
