//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.UserControls {
    
    public partial class HairShopEntryControl {
        protected System.Web.UI.WebControls.Label lblHairShopName;
        protected System.Web.UI.WebControls.Label lblHairShopAddress;
        protected System.Web.UI.WebControls.Label lblLocationMapUrl;
        protected System.Web.UI.WebControls.Label lblSquare;
        protected System.Web.UI.WebControls.Label lblIsPostStation;
        protected System.Web.UI.WebControls.Label lblIsPostMachine;
        protected System.Web.UI.WebControls.Label lblHairShopOpenTime;
        protected System.Web.UI.WebControls.Label lblHairShopType;
        protected System.Web.UI.WebControls.Label lblProduct;
        protected System.Web.UI.WebControls.Panel p1;
        protected System.Web.UI.WebControls.Label lblCouponPic;
        protected System.Web.UI.WebControls.Label lblPrintNum;
        protected System.Web.UI.WebControls.Label lblPrintCoupon;
        protected System.Web.UI.WebControls.Panel p2;
        protected System.Web.UI.HtmlControls.HtmlInputText txtCouponEmail;
        protected System.Web.UI.WebControls.ImageButton imgBtnCouponSubmit;
        protected System.Web.UI.WebControls.Label lblHairShopPhoneNum;
        protected System.Web.UI.WebControls.Label lblHairShopDiscount;
        protected System.Web.UI.WebControls.Label lblComment;
        protected System.Web.UI.WebControls.Label lblStore;
    }
}
