//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Admin {
    
    public partial class EngineerOpusInfo {
        protected System.Web.UI.HtmlControls.HtmlForm form1;
        protected System.Web.UI.WebControls.TextBox txtOpusName;
        protected System.Web.UI.WebControls.FileUpload frontsidePic;
        protected System.Web.UI.WebControls.Button btn1;
        protected System.Web.UI.WebControls.Label lbl1;
        protected System.Web.UI.WebControls.Label lbl1new;
        protected System.Web.UI.WebControls.Image i1;
        protected System.Web.UI.WebControls.FileUpload flanksidePic;
        protected System.Web.UI.WebControls.Button btn2;
        protected System.Web.UI.WebControls.Label lbl2;
        protected System.Web.UI.WebControls.Label lbl2new;
        protected System.Web.UI.WebControls.Image i2;
        protected System.Web.UI.WebControls.FileUpload backsidePic;
        protected System.Web.UI.WebControls.Button btn3;
        protected System.Web.UI.WebControls.Label lbl3;
        protected System.Web.UI.WebControls.Label lbl3new;
        protected System.Web.UI.WebControls.Image i3;
        protected System.Web.UI.WebControls.FileUpload assistancePic;
        protected System.Web.UI.WebControls.Button btn4;
        protected System.Web.UI.WebControls.Label lbl4;
        protected System.Web.UI.WebControls.Label lbl4new;
        protected System.Web.UI.WebControls.Image i4;
        protected System.Web.UI.WebControls.CheckBoxList chkJPList;
        protected System.Web.UI.WebControls.CheckBoxList chkMXList;
        protected System.Web.UI.WebControls.CheckBoxList chkFXList;
        protected System.Web.UI.WebControls.DropDownList ddlHairNature;
        protected System.Web.UI.WebControls.DropDownList ddlHairQuantity;
        protected System.Web.UI.WebControls.DropDownList ddlFaceStyle;
        protected System.Web.UI.WebControls.DropDownList ddlSex;
        protected System.Web.UI.WebControls.DropDownList ddlHairStyleClassName;
        protected System.Web.UI.WebControls.DropDownList ddlTemperament;
        protected System.Web.UI.WebControls.DropDownList ddlOccasion;
        protected System.Web.UI.WebControls.TextBox txtDesc;
        protected System.Web.UI.WebControls.Button btnAdd;
    }
}
