//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Admin {
    
    public partial class PictureStoreAdd {
        protected System.Web.UI.HtmlControls.HtmlForm form1;
        protected System.Web.UI.WebControls.TextBox txtPictureStoreName;
        protected System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator1;
        protected System.Web.UI.WebControls.TextBox txtPictureStoreTag;
        protected System.Web.UI.WebControls.Label lblRedInfo1;
        protected System.Web.UI.WebControls.TextBox txtBbsurl;
        protected System.Web.UI.WebControls.CheckBoxList chkJPList;
        protected System.Web.UI.WebControls.CheckBoxList chkMXList;
        protected System.Web.UI.WebControls.CheckBoxList chkFXList;
        protected System.Web.UI.WebControls.DropDownList ddlHairNature;
        protected System.Web.UI.WebControls.DropDownList ddlHairQuantity;
        protected System.Web.UI.WebControls.DropDownList ddlFaceStyle;
        protected System.Web.UI.WebControls.DropDownList ddlSex;
        protected System.Web.UI.WebControls.DropDownList ddlHairStyleClassName;
        protected System.Web.UI.WebControls.DropDownList ddlTemperament;
        protected System.Web.UI.WebControls.DropDownList ddlOccasion;
        protected System.Web.UI.WebControls.TextBox txtPictureStoreDescription;
        protected System.Web.UI.HtmlControls.HtmlInputFile uploadpicsmall;
        protected System.Web.UI.WebControls.FileUpload uploadpic1;
        protected System.Web.UI.WebControls.Button btnPicUpload;
        protected System.Web.UI.WebControls.Label lblRedInfo;
        protected System.Web.UI.WebControls.Button btnSubmit;
        protected System.Web.UI.WebControls.Label picString;
        protected System.Web.UI.WebControls.Label pic;
        protected System.Web.UI.WebControls.Label picsmall;
    }
}
