//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Admin {
    
    public partial class PictureStoreAdmin {
        protected System.Web.UI.HtmlControls.HtmlForm form1;
        protected System.Web.UI.WebControls.DropDownList ddlQuery;
        protected System.Web.UI.WebControls.TextBox txtQueryName;
        protected System.Web.UI.WebControls.Label lblQueryNameSpace;
        protected System.Web.UI.WebControls.Label lblStartTime;
        protected DMSTime.DMSTimeControl txtStartTime;
        protected System.Web.UI.WebControls.Label lblEndTime;
        protected DMSTime.DMSTimeControl txtEndTime;
        protected System.Web.UI.WebControls.Label lblTimeSpace;
        protected System.Web.UI.WebControls.Button btnQuery;
        protected System.Web.UI.WebControls.DropDownList ddlOrderWay;
        protected System.Web.UI.WebControls.Button btnSelect;
        protected System.Web.UI.WebControls.Button btnAdd;
        protected System.Web.UI.WebControls.Button btnRecommand;
        protected System.Web.UI.WebControls.DataGrid dg;
        protected System.Web.UI.WebControls.LinkButton PageFirst;
        protected System.Web.UI.WebControls.LinkButton PagePrev;
        protected System.Web.UI.WebControls.LinkButton PageNext;
        protected System.Web.UI.WebControls.LinkButton PageLast;
        protected System.Web.UI.WebControls.Label CountPage;
        protected System.Web.UI.WebControls.TextBox ispages;
        protected System.Web.UI.WebControls.DropDownList thispages;
        protected System.Web.UI.WebControls.Label Page_nPage;
        protected System.Web.UI.WebControls.Label Page_nRecCount;
        protected System.Web.UI.WebControls.Label Page_nRecCount_1;
        protected System.Web.UI.WebControls.Label Page_strSQL;
    }
}
