//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Admin {
    
    public partial class ProductEdit {
        protected System.Web.UI.HtmlControls.HtmlHead Head1;
        protected System.Web.UI.HtmlControls.HtmlForm form1;
        protected System.Web.UI.WebControls.TextBox txtProductName;
        protected System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator1;
        protected System.Web.UI.WebControls.TextBox txtProductRawPrice;
        protected System.Web.UI.WebControls.RegularExpressionValidator RegularExpressionValidator1;
        protected System.Web.UI.WebControls.TextBox txtProductPrice;
        protected System.Web.UI.WebControls.RegularExpressionValidator RegularExpressionValidator2;
        protected System.Web.UI.WebControls.TextBox txtProductDiscount;
        protected System.Web.UI.WebControls.RegularExpressionValidator RegularExpressionValidator3;
        protected System.Web.UI.WebControls.TextBox txtProductTag;
        protected System.Web.UI.WebControls.Label lblRedInfo1;
        protected System.Web.UI.WebControls.TextBox txtProductDescription;
        protected System.Web.UI.WebControls.TextBox txtCompany;
        protected System.Web.UI.WebControls.TextBox txtCompanyDescription;
        protected System.Web.UI.WebControls.Button btnSubmit;
    }
}
