//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Admin {
    
    public partial class EngineerOpusInfo {
        protected System.Web.UI.HtmlControls.HtmlForm form1;
        protected System.Web.UI.WebControls.TextBox txtOpusName;
        protected System.Web.UI.WebControls.FileUpload frontsidePic;
        protected System.Web.UI.WebControls.Label lbFPic;
        protected System.Web.UI.WebControls.FileUpload flanksidePic;
        protected System.Web.UI.WebControls.Label lbFlPic;
        protected System.Web.UI.WebControls.FileUpload backsidePic;
        protected System.Web.UI.WebControls.Label lbBPic;
        protected System.Web.UI.WebControls.FileUpload assistancePic;
        protected System.Web.UI.WebControls.Label lbAPic;
        protected System.Web.UI.WebControls.DropDownList listHairStyle;
        protected System.Web.UI.WebControls.DropDownList listFaceType;
        protected System.Web.UI.WebControls.DropDownList listHairType;
        protected System.Web.UI.WebControls.DropDownList listHairItem;
        protected System.Web.UI.WebControls.TextBox txtDesc;
        protected System.Web.UI.WebControls.Button btnAdd;
    }
}
