//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Admin {
    
    public partial class HairEngineerEdit {
        protected System.Web.UI.HtmlControls.HtmlHead Head1;
        protected System.Web.UI.HtmlControls.HtmlForm form1;
        protected System.Web.UI.WebControls.TextBox txtHairEngineerName;
        protected System.Web.UI.WebControls.CheckBox chkIsImportant;
        protected System.Web.UI.WebControls.RadioButtonList rBtnListHairEngineerSex;
        protected System.Web.UI.WebControls.TextBox txtHairEngineerRawPrice;
        protected System.Web.UI.WebControls.TextBox txtHairEngineerPrice;
        protected System.Web.UI.WebControls.DropDownList ddlHairShopClass;
        protected System.Web.UI.HtmlControls.HtmlInputFile fileLogo;
        protected System.Web.UI.WebControls.Button btnPicSubmit;
        protected System.Web.UI.WebControls.Label lblpicSring;
        protected System.Web.UI.WebControls.Label lblPic;
        protected System.Web.UI.WebControls.DropDownList ddlHairShop;
        protected System.Web.UI.WebControls.TextBox txtHairEngineerYear;
        protected System.Web.UI.WebControls.TextBox txtHairEngineerSkill;
        protected System.Web.UI.WebControls.TextBox txtHairEngineerTag;
        protected System.Web.UI.WebControls.TextBox txtHairEngineerDescription;
        protected System.Web.UI.WebControls.Button btnSubmit;
    }
}
