//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Admin {
    
    public partial class HairShopAdd {
        protected System.Web.UI.HtmlControls.HtmlHead Head1;
        protected System.Web.UI.HtmlControls.HtmlForm form1;
        protected System.Web.UI.WebControls.TextBox txtHairShopName;
        protected System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator1;
        protected System.Web.UI.WebControls.TextBox txtHairShopShortName;
        protected System.Web.UI.WebControls.DropDownList ddlTypeTable;
        protected System.Web.UI.WebControls.TextBox txtHairShopWebSite;
        protected System.Web.UI.WebControls.TextBox txtHairShopEmail;
        protected System.Web.UI.WebControls.TextBox txtHairShopDiscount;
        protected System.Web.UI.WebControls.TextBox tbHairCutPrice;
        protected System.Web.UI.WebControls.TextBox tbHairCutDiscount;
        protected System.Web.UI.WebControls.TextBox tbMarcelPrice;
        protected System.Web.UI.WebControls.TextBox tbMarclDiscount;
        protected System.Web.UI.WebControls.TextBox tbHairDyePrice;
        protected System.Web.UI.WebControls.TextBox tbHairDyeDiscount;
        protected System.Web.UI.WebControls.TextBox tbShapePrice;
        protected System.Web.UI.WebControls.TextBox tbShapeDiscount;
        protected System.Web.UI.WebControls.TextBox tbConservationPrice;
        protected System.Web.UI.WebControls.TextBox tbConservationDiscount;
        protected System.Web.UI.WebControls.TextBox TextBox4;
        protected System.Web.UI.WebControls.TextBox tbLocation;
        protected System.Web.UI.WebControls.FileUpload fileLogo;
        protected System.Web.UI.WebControls.TextBox txtHairShopCreateTime;
        protected System.Web.UI.WebControls.DropDownList ddlCity;
        protected System.Web.UI.WebControls.DropDownList ddlMapZone;
        protected System.Web.UI.WebControls.DropDownList ddlHotZone;
        protected System.Web.UI.WebControls.TextBox txtHairShopAddress;
        protected System.Web.UI.WebControls.TextBox txtHairShopPhoneNum;
        protected System.Web.UI.WebControls.TextBox txtHairShopOpenTime;
        protected System.Web.UI.WebControls.TextBox txtHairShopTag;
        protected System.Web.UI.WebControls.CheckBoxList chkListWorkRange;
        protected System.Web.UI.WebControls.CheckBox chkMarcel;
        protected System.Web.UI.WebControls.CheckBox chkDye;
        protected System.Web.UI.WebControls.CheckBox chkCut;
        protected System.Web.UI.WebControls.CheckBox chkIsJoin;
        protected System.Web.UI.WebControls.TextBox txtMemberInfo;
        protected System.Web.UI.WebControls.CheckBox chkIsPostStation;
        protected System.Web.UI.WebControls.CheckBox chkIsPostMachine;
        protected System.Web.UI.WebControls.TextBox txtDescription;
        protected System.Web.UI.WebControls.Label lblProductInfo;
        protected System.Web.UI.WebControls.CheckBoxList chkList;
        protected System.Web.UI.WebControls.Button btnSubmit;
    }
}
