//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Admin {
    
    public partial class HairShopAddNext1 {
        protected System.Web.UI.HtmlControls.HtmlForm form1;
        protected System.Web.UI.HtmlControls.HtmlInputFile out1c;
        protected System.Web.UI.WebControls.Label lbFPic;
        protected System.Web.UI.HtmlControls.HtmlInputFile out2c;
        protected System.Web.UI.WebControls.Label lbFlPic;
        protected System.Web.UI.HtmlControls.HtmlInputFile out3c;
        protected System.Web.UI.WebControls.Label lbBPic;
        protected System.Web.UI.HtmlControls.HtmlInputFile inner1c;
        protected System.Web.UI.WebControls.Label Label1;
        protected System.Web.UI.HtmlControls.HtmlInputFile inner2c;
        protected System.Web.UI.WebControls.Label Label2;
        protected System.Web.UI.HtmlControls.HtmlInputFile inner3c;
        protected System.Web.UI.WebControls.Label Label3;
        protected System.Web.UI.WebControls.Button btnSubmit;
    }
}
