//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.UserControls {
    
    public partial class HairShopDescription {
        protected System.Web.UI.WebControls.Label lblHairShopName;
        protected System.Web.UI.WebControls.Label lbllHairShopPic;
        protected System.Web.UI.WebControls.Label lblHairShopDescription;
        protected System.Web.UI.WebControls.Label lblHairEngineerPic;
        protected System.Web.UI.WebControls.Label lblHairEngineerDescription;
        protected System.Web.UI.WebControls.Label lblMemberInfo;
    }
}
