//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web {
    
    public partial class SearchHeadPage {
        protected System.Web.UI.HtmlControls.HtmlForm form1;
        protected Web.UserControls.SearchHead searchHead;
    }
}
