//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web {
    
    public partial class HairShopContent {
        protected Web.UserControls.SearchHead searchHead;
        protected Web.UserControls.HairShopEntryControl hairShopEntryControl;
        protected Web.UserControls.HairShopDescription hairShopEntryDescription;
        protected Web.UserControls.HairShopEngineerList hairShopEngineerList;
        protected Web.UserControls.HairShopWorkList hairShopWorkList;
    }
}
