//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.UserControls {
    
    public partial class HairShopVoteControl {
        protected System.Web.UI.UpdatePanel updatePanel1;
        protected System.Web.UI.WebControls.LinkButton linkBtnGood;
        protected System.Web.UI.WebControls.Label lblGood;
        protected System.Web.UI.WebControls.Label lblGoodNum;
        protected System.Web.UI.WebControls.LinkButton linkBtnNormal;
        protected System.Web.UI.WebControls.Label lblNormal;
        protected System.Web.UI.WebControls.Label lblNormalNum;
        protected System.Web.UI.WebControls.LinkButton linkBtnBad;
        protected System.Web.UI.WebControls.Label lblBad;
        protected System.Web.UI.WebControls.Label lblBadNum;
    }
}
