//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web {
    
    public partial class HairShopList {
        protected Web.UserControls.RecommandHairShopList recommandHairShopList;
        protected Web.UserControls.HairShopListControl hairShopListControl;
        protected Web.UserControls.HotHairShopList hotHairShopList;
        protected Web.UserControls.HotCouponList2 hotCouponList;
    }
}
